### ISSUE TITLE
Jailed validators dont display users's stacked Fuse

### ISSUE THREAD

**Issue by lampalork85** [fuseio/fuse-staking#11]
It seem that jailed validator dont show the user's stacked fuse.

![image](https://user-images.githubusercontent.com/38051081/141291249-a056b9e0-3403-41ff-9017-b9ea510a98ae.png)

All display 0 stacked fuse but when we use the fuse explorer we can see that there is user's stacked fuse on some of this.
This problem is major because user can't unstake them.

**Comment by lampalork85** [comment]
corrected by https://github.com/fuseio/fuse-staking/pull/12/

![image](https://user-images.githubusercontent.com/38051081/141464048-6114b67d-9bfd-451b-b917-d1a75e734c38.png)

**Comment by Andrew-Pohl** [comment]
Thanks for pointing it out @lampalork85
